---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: canarydeployments.webapp.wgjak47.me
spec:
  group: webapp.wgjak47.me
  names:
    kind: CanaryDeployment
    plural: canarydeployments
  scope: ""
  subresources:
    status: {}
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
